# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('reading_sonic_empty', models.FloatField(default=1.0)),
                ('reading_sonic_full', models.FloatField(default=0.0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('rating', models.IntegerField(default=-1)),
                ('message', models.CharField(default='no_message', max_length=500)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_reading', models.FloatField(default=-1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Container')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='no_first_name', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
