# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181123_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='lat',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='container',
            name='lng',
            field=models.FloatField(default=-1),
        ),
    ]
