# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-23 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181123_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='location_string',
            field=models.CharField(default='no_location_string', max_length=300),
        ),
    ]
